### ISSUE TITLE
Checkout issue in Hybris 1811 (on-prem)

### ISSUE THREAD

**Issue by samgga69** [Adyen/adyen-hybris#119]
**Hybris version**: 1811 (on-prem)
**Plugin version**: 4.2.0
**Description**

I am currently performing testing of Adyen plugin in my local Hybris instance, but I have below issues:

1. No further payment details prompt during checkout
![image](https://user-images.githubusercontent.com/49187390/58309644-64be3980-7e37-11e9-8234-7b95996b568b.png)

2. URL Invalid during server communication setup
![image](https://user-images.githubusercontent.com/49187390/58309769-ac44c580-7e37-11e9-8d8f-2ee9b4d0e6c5.png)
URL entered: https://electronics.local:9002/yacceleratorstorefront/electronics/en/adyen/v6/notification/json

3. Is it correct by entering below domain for generating origin key? 
https://electronics.local:9002/

Overall, does the Adyen plugin work for Hybrs 1811 on-prem?
Kindly advise.

Thank you!

**Comment by rkewlani** [comment]
Hi @samgga69 ,
Please contact our support team for any configuration related questions. This portal is only for development related issues/bugs.
Thanks,
Rajni
Adyen
