### ISSUE TITLE
createOrderFromPaymentsResponse throws nullPointer when nu additionalData in PaymentsResponse

### ISSUE THREAD

**Issue by pjdelaere** [Adyen/adyen-hybris#152]
**Hybris version**: 18.11
**Plugin version**: 6.2.0
When a payment for eg Visa is done and the result is authorized the DefaultAdyenCheckoutFacade.createOrderFromPaymentsResponse will create an order from the paymentsResponse. However it will set the PosReceipt (even if not Pos payment) based of the PaymentsResponse.additionalData. 
In my response this is null, causing a nullPointerException. Shouldn't this check for Null?

Example of response I got
`class PaymentsResponse {
    additionalData: null
    details: null
    fraudResult: null
    paymentData: null
    pspReference: 883572010021095C
    redirect: null
    refusalReason: null
    refusalReasonCode: null
    resultCode: Authorised
    serviceError: null
    authResponse: null
    merchantReference: 000000112013
    outputDetails: null
    authentication: null
    threeDS2Result: null
    action: null
}`

**Comment by rkewlani** [comment]
Hi @ pjdelaere, 
We are looking into this.
Thanks,
Rajni

**Comment by rkewlani** [comment]
Hi @pjdelaere ,
It was not failing for us because there was always additionaldata present in response. However, it is good to put additional check. Here is the fix for this :
https://github.com/Adyen/adyen-hybris/pull/153
We will merge it soon and release it.
Regards,
Rajni
