### ISSUE TITLE
HPP in version 6.2.1

### ISSUE THREAD

**Issue by pjdelaere** [Adyen/adyen-hybris#155]
**Hybris version**: 1811
**Plugin version**: 6.2.1
**Description**
Can we still use HPP? Cause I don't see it anywhere in the code except for PayPal?

**Comment by rkewlani** [comment]
Hi @pjdelaere,
HPP is depcrated solution we now build on top of checkout. So it is not recommended. If you have further questions on this, please contact our support team because this platform is for code related issue reportings.
Regards,
Rajni
Adyen.
