### ISSUE TITLE
Apple pay amount mismatch.

### ISSUE THREAD

**Issue by saurabhranaborn** [Adyen/adyen-hybris#166]
**Hybris version**:6.5.0
**Plugin version**: 6.1.0
**MerchantAccount**: LornaJaneUAT
**Description**
We are trying to integrate applepay. We have followed all the steps mentioned given in the following documentation:
https://docs.adyen.com/payment-methods/apple-pay/web-component

We are successfully able to retrieve the apple pay token and use it to make a call to /payments endpoint. But we get API exception. On further inquiring with Adyen support  they told us they can see the following error in their logs whee it says the following :
**Amount mismatch, received AUD 129.54 expected USD 129.54**
We were told that the currency being different may be the issue. Later on we were told that currency can be different. 
But i can assure you we are passing currency as AUD. In line with the adyen documentation we pass the amount and currency only in the following scenarios:
1. When we have to create the apple checkout component in the js.
2. When we have to make a call to /payments after we pass it the token.

The only call that we make to apple from our servers is to get the apple session.

I am attaching a sample request.

This is the final hurdle we are facing in integrating applepay. Any help would be much appreciated.
P.S: Please don't get confused with the amount in the request we are passing 6599 as the amount.
Thanks,
Saurabh
[Request (1).txt](https://github.com/Adyen/adyen-hybris/files/4125614/Request.1.txt)
![image](https://user-images.githubusercontent.com/25197184/73318265-dbc98e80-425e-11ea-91c1-db61e38f3edb.png)

**Comment by rkewlani** [comment]
Hi @saurabhranaborn,
Thanks for contacting us. Can you please contact our technical support team for this query. This platform is just for technical discussion on existing code and raising the issues in code. Since it is more specific to your use case, our technical support team will help you.
Thanks,
Adyen
