### ISSUE TITLE
Cart duplication in 3D secure redirection 

### ISSUE THREAD

**Issue by bazidev** [Adyen/adyen-hybris#167]
**Hybris version**: 1905
**Plugin version**: 6.2.0
**Description**
When using 3dS cards The lockSessionCart() method creates another empty cart for registered users while locking the cart. this is causing two problems :

- while the restoreSessionCart() has no operation to remove the additional cart, the card persists in the DB and in the Backoffice.

- after redirection to the 3dS link and going back using the browser back button, the user found himself losing his cart because it's not restored in this case.

here is the code responsible of creating additional carts :
`//Refresh session for registered users
if (!getCheckoutCustomerStrategy().isAnonymousCheckout()) {
getCartService().getSessionCart();
}`

Thanks in advance

**Comment by rkewlani** [comment]
Hi @bazidev,
We do not create additional cart in our code in lockSessionCart(). We are just getting it from session. Also, please contact our support team if you are facing any problems in cart restorations. I also observed you are using 1905 hybris version which is currently not supported in our plugin.
Thanks.

**Comment by bazidev** [comment]
Hello @rkewlani 
I know you are getting the cart from the session, but just before that you're removing the cart.
I just want to know why do you call the getCartService().getSessionCart(); just after removing the cart.

`   @Override
    public void lockSessionCart() {
        getSessionService().setAttribute(SESSION_LOCKED_CART, cartService.getSessionCart());
        getSessionService().removeAttribute(SESSION_CART_PARAMETER_NAME);

        //Refresh session for registered users
        if (!getCheckoutCustomerStrategy().isAnonymousCheckout()) {
            getCartService().getSessionCart();
        }
    }
`

what do you mean by `        //Refresh session for registered users`?

**Comment by rkewlani** [comment]
Hi @bazidev ,
We are removing old cart and creating new cart in user session so that user is not able to see that and modify that while payment is in process. Removal here is just removal from user view. We are not removing the cart from backend. 
I hope it answers your question.
Thanks,
Adyen
