### ISSUE TITLE
3DS2 test page SameSite cookies. (Causes logout)

### ISSUE THREAD

**Issue by bazidev** [Adyen/adyen-hybris#168]
In the last two days i've been facing a random bug, at the end of the Adyen Checkout, and after going to the challenge site (**for 3dS2**) and performing the challenge and then returning to hybris, my website performs a random logout before reaching the **/3ds2-adyen-response**. i was able to reproduce the bug on chrome  :
1 - Version 80.0.3987.0 (Developer Build) (64-bit) **[default settings]**
2 - Version 82.0.4084.0 (Official Build) canary (64-bit) **[default settings]**
3 - Version 80.0.3987.132 (Official Build) (64-bit) **[enable  #same-site-by-default-cookies flage and #enable-removing-all-third-party-cookies and #cookies-without-same-site-must-be-secure flags]**

After searching on the web I found out that chrome is launching a major update on SameSite cookies, [sameSite Update](https://www.chromium.org/updates/same-site)

the new update reached already some versions of Chrome and coming to the rest in the next days, firefox also will do the same thing.

Chrome is providing some debug tools for the new configurations, details here : [Tips for testing and debugging SameSite-by-default and “SameSite=None; Secure” cookies
](https://www.chromium.org/updates/same-site/test-debug)

here is a screen of the debug website on my chrome (3 - Version 80.0.3987.132 (Official Build) (64-bit) **with flags enabled !!**)  and it's the same for 1 and 2:
![image](https://user-images.githubusercontent.com/16518671/76538339-71bc2000-647f-11ea-8fea-79063db02de8.png)
As you can see if the **Set-Cookie** doesn't have a **SameSite** Configuration it will be excluded by default in a **cross-site** context! 

The Chrome without those flags enabled (**where the bug is not reproductive**) looks like this :
![image](https://user-images.githubusercontent.com/16518671/76539916-b5b02480-6481-11ea-85bd-b2415ab96542.png)

And while Hybris connexion with 3ds2 website is based on cookies it's mostly because of some kind of missing cookies config that lead to this bug.

As you can see in the below example when going back to the **returnUrl** the **JSessionId** cookie gets filtred, which is causing hybris to create a new JSessionId and lose the current session.
![image](https://user-images.githubusercontent.com/16518671/76538094-0b370200-647f-11ea-8192-f72ea786a0cf.png)

we have already excluded the adyen urls from the crsf checklist as it's mentioned in the documentation, but we don't know how to fix this ! 

Note : here is the card info for all of the tests 
Mastercard | 5454 5454 5454 5454 | 03/2030 | 737

Thanks in advance

**Comment by rkewlani** [comment]
Hi @bazidev,
Thanks for writing to us. Please contact our support team for this issue. 
Thanks,
Adyen

**Comment by bazidev** [comment]
Hi @rkewlani,

Thank you for your feedback,
Just to clarify for others this bug is related to the JSESSION cookie configuration, it's a server-side bug related to tomcat configuration in Hybris.
