### ISSUE TITLE
The API key column cannot hold an API key.

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-hybris#172]
**Hybris version**: 6.6.0
**Plugin version**: 6.4.0
**Description**
The API key column model definition cannot hold an API key.

Currently the api key column is defined as just String which results to varchar/char/varchar2 of a size of 200, the API key is quite bigger, so in order to use the plugin right now you have to make change in the model or alter the table which is less then ideal.

**Comment by rkewlani** [comment]
Hi @gochev , 
Thanks for writing to us. We will look into it and will get back to you.

Regards,
Adyen

**Comment by rkewlani** [comment]
Hi @gochev , 
We verified this and indeed size should be updated. If you already have made changes in your system, we really appreciate if you want to create a pull request in our repository. If not, we are working on this and  will change it soon. 
Thanks for your efforts.
Regards,
Adyen

**Comment by gochev** [comment]
Hello @rkewlani  as of now I just edited my schema and I haven't changed the items.xml, so thats why I haven't created a PR :) 
but if the PRs are an option I will try to create PRs for other issues if I find any.

Also a note since you are using tags and not branches I hope ones a fix is done it will be back ported to older versions ? Not sure how this will work since as I said you are using tags and not branches, at least in this github repo.

**Comment by rkewlani** [comment]
Hi @gochev,
we are working on this and will let you know once it is done. 
About branch, we always make new release and it won't be ported to old version. It will be a new version. Feature branch is also created for each change and you may also refer branch in case you want to see specific change. We will keep you posted.
Thanks,
Adyen

**Comment by rkewlani** [comment]
Hi @gochev,
We have fixed issue on following PR:
https://github.com/Adyen/adyen-hybris/pull/178
It will be only applicable for new installations due to limitations on hybris side.
Regards,
Adyen
