### ISSUE TITLE
The Card Type is not populated and not send to the server

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-hybris#179]
**Describe the bug**
The CardType field is not populated properly and not send to the server

**To Reproduce**
1. Go to 'select payment step'
2. Fill some credit card details
3. Open Networking Manager (f12) 
4. Submit 
5. Check the card type value

**Expected behavior**
The card type to be filled e.g. visa

**Hybris Plugin version 6.4.0**

**Note:**
The problem happens because of this method :
    getCardType: function () {
            return $( '#adyen_combo_card_type' ).val();
        },

Which is inside adyen.checkout.js 

As you can see it depends on a combo box for the type but the form no longer have combo box.. :) the credit card is an svg shown inside the card number, this combo doesn't exist and returns 'undefined'

**Comment by rkewlani** [comment]
Thanks @gochev for writing to us. We are looking into it and will keep you posted !
Regards,
Adyen

**Comment by rkewlani** [comment]
Hi @gochev,
This is not an issue. We have combo card. If you select brazil and use BRL currency, you will see combo card. Card type is not needed in other cases.
Regards,
Rajni
