### ISSUE TITLE
AdyenCaptureCommand doesnt work for orders with custom Order Code generator

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-hybris#182]
**Describe the bug**

The adyen capture command depends on the order code to work, however with custom order code generator this code can be everything basically making all capture transactions to fail.

**To Reproduce**
1. Configure order code generator (read bellow)
2. Place an order
3. Check the AdyenCaptureCommand will not find any order.
4. See the capture doesnt happen

**Expected behavior**
The capture to happen :) 

**Additional context**
Happens on ALL hybris versions ( I am aware of this order  code functionality since Hybris 4 in 2009.)

In order to read more about this Hybris functionality you can read here https://hybrisarchitect.com/how-to-configure-the-order-number-range-in-sap-hybris-commerce-using-groovy/

99% of the Merchants using hybris have existing website, so they want to at least start not from 1000 but from other big number. 
**How to do that in short story :**

Add this properties to your local.properties : 

keygen.order.code.digits=10

keygen.order.code.start=0055000000

keygen.order.code.numeric=true

numberseries.cache.size.order_code=1 

This are just an example.

Then start Hybris and reset the orderCodeGenerator. Easiest is to open HAC and execute a groovy script with this line : spring.getBean("orderCodeGenerator").reset();

Then the orders will start from 0055000000 but you can do many things even have a non numeric codes. You can even override  <bean id="orderCodeGenerator" class="de.hybris.platform.servicelayer.keygenerator.impl.PersistentKeyGenerator"> and generate whatever you want, so you cannot depend on the CART code.

**Long story:**

In hybris when a CART becomes an ORDER it doesnt use the card code anymore, but instead it can have ANY code. So you should **NOT** depend on the **cart code** in the AdyenCaptureCommand line 67. 

Bug is for Plugin version 6.4.0 and tested on Hybris 6.6

**Comment by rkewlani** [comment]
Hi @gochev,
Thanks for writing to us. We will look into it and let you know.
Regards,
Rajni

**Comment by rkewlani** [comment]
Hi @gochev,
AdyenCaptureCommand code is based on default logic Adyen uses to map cartId and OrderId. If you have done customisations to generate orderId then you will need to reflect this customisation at other places as well. 

Regards,
Rajni
