### ISSUE TITLE
Going back from 3DS page leads to an empty card in case of GUEST checkout

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-hybris#183]
**Describe the bug**
When you hit BROWSER back from the 3DS page you land on an empty card if anonymous.

**To Reproduce**
1. Start order and select card payment with guest/anonymous user.
2. Enter 3DS (1) card details
3. Wait to be redirected to the 3DS page.
4. An empty cart is displayed (the cart is lost)

**Expected behavior**

The cart to not be lost and to be returned to the summary page so maybe you can select other payment method.

**Additional context**
This is not related to any browsers or OS.

Plugin version is 6.4.0 , Hybris version we use is 6.6

**Comment by rkewlani** [comment]
Hi @gochev,
Thanks for writing to us. We will look into it and let you know.
Regards,
Rajni

**Comment by rkewlani** [comment]
Hi @gochev,
We have created internal tickets for fixing these issues. We will keep you posted.
Regards,
Adyen

**Comment by rkewlani** [comment]
Hi @gochev,
We tried some options. but due to technical limitations it cannot be fixed.
Regards,
Rajni
