### ISSUE TITLE
Going back from 3DS2 page leads to an CONFIRM form resubmission

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-hybris#184]
**Describe the bug**
The bug is related to https://github.com/Adyen/adyen-hybris/issues/183 but for 3DS2. Please resolve this ones  https://github.com/Adyen/adyen-hybris/issues/183 is done otherwise you will hit  https://github.com/Adyen/adyen-hybris/issues/183

User should be able to go back from the 3DS2 or 3DS page and select different payment method. Ones the https://github.com/Adyen/adyen-hybris/issues/183 is fixed for 3DS then we have a new issue for 3DS2 related to the fact that the adyen plugin is doing POST.

**To Reproduce**
1. Start checkout with GUEST user and select a Card Payment
2.  Fill the details with a 3DS2 card
3.  Make browser back 
4. See the screenshot.

**Expected behavior**
To see the previous page displayed normally with an option to select a different payment method or card details.

**Screenshots**
<img width="741" alt="Screen Shot 2020-06-01 at 11 10 58" src="https://user-images.githubusercontent.com/5537142/83399295-de004d00-a3f8-11ea-9d1e-fdb28a226c5f.png">

**Additional context**
The bug is not related to browser or OS. Plugin version 6.4.0 Hybris 6.6

P.S. the bug happens because you are doing POST before the redirect to the 3DS2 page. So when the user hits BACK he is on the POST request.

**Comment by rkewlani** [comment]
Hi @gochev,
Thanks for writing to us. We will look into it and let you know.
Regards,
Rajni

**Comment by rkewlani** [comment]
Hi @gochev,
We have created internal ticket for fixing this issues. We will keep you posted.
Regards,
Adyen

**Comment by rkewlani** [comment]
We tried to reproduce this issue and could not do it by given steps. We are not getting this error on immediate "back" button. If you press back button, you will go to /cart page.
 If you go back and forth from summary or cart to 3ds challenge page then you will get this error. It is not recommended to do that. Back and forward actions also clear payments data for security reasons. However user should be able to recover the cart and you have already raised it in other issue so we are closing this issue here.

**Comment by gochev** [comment]
Hello @rkewlani there is a pattern called POST REDIRECT GET basically each time you do post.. you should always redirect and land the customer on GET request so the customer should never see a browser in a POST request, so the customer should never see "CONFIRM Form resubmission", however it looks the POST, REDIRECT, GET pattern that exists since well the beginning of server side webpages is not something Adyen is considering a good practice :)
