### ISSUE TITLE
Function include on Array, not available for Internet Explorer 11

### ISSUE THREAD

**Issue by sylvainfontaine** [Adyen/adyen-hybris#214]
On Browser IE 11, the javascript instruction include is not available.
On adyen.checkout.js in the module accelatoraddon 
I think that it would be necessary to change the function include by an indexOf on the array

['eps','ideal'].includes(paymentMethod)  --> ['eps','ideal'].indexOf(paymentMethod) >= 0

**Comment by rkewlani** [comment]
Hi @sylvainfontaine ,
Thanks for writing to us. We are looking into it.

Regards,
Adyen

**Comment by martinsrenato** [comment]
Hi @sylvainfontaine 
We removed the use of `includes` method. This was included on the changes made for a different feature, but you can check it on [this PR](https://github.com/Adyen/adyen-hybris/commit/702c33ef586e467f24a9b7f0424f81eeb12316f7#diff-d3785f96b2be412f4136f6061bdb95c905ef10dfbf2d932ca477ac66061c6315).

Regards,
Renato
Adyen

**Comment by rcaroen** [comment]
Thanks for that

Tape à l'oeil

**Comment by manojdaffodil29** [comment]
Hi
i am integrating adyen payment on my site and in adyen js require statement is giving error in IE11
window.Promise=require("promise/lib/es6-extensions.js")
js file https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/4.0.0/adyen.js
can you please look into this issue
