### ISSUE TITLE
Null Pointer Exception in AdyenRequestFactory

### ISSUE THREAD

**Issue by abonforti** [Adyen/adyen-hybris#232]
**Describe the bug**
When the **ConfigurationService** is injected in **AdyenRequestFactory**, it gets injected as null, hence, a NPE is raised.

**To Reproduce**
1. Pick adyenv6core and import into the workspace
2. Build and start
3. When the flow is engaged, a NPE is raised

**Expected behavior**
ConfigurationService shouldn't be injected as null.

**Screenshots**
```
INFO   | jvm 1    | main    | 2021/01/04 13:29:30.989 | java.lang.NullPointerException: null
INFO   | jvm 1    | main    | 2021/01/04 13:29:30.990 |    at com.adyen.v6.factory.AdyenRequestFactory.getPlatformVersion(AdyenRequestFactory.java:949) ~[classes/:?]
INFO   | jvm 1    | main    | 2021/01/04 13:29:30.990 |    at com.adyen.v6.factory.AdyenRequestFactory.updateApplicationInfoPos(AdyenRequestFactory.java:310) ~[classes/:?]
INFO   | jvm 1    | main    | 2021/01/04 13:29:30.990 |    at com.adyen.v6.factory.AdyenRequestFactory.updateApplicationInfoEcom(AdyenRequestFactory.java:295) ~[classes/:?]
INFO   | jvm 1    | main    | 2021/01/04 13:29:30.991 |    at com.adyen.v6.factory.AdyenRequestFactory.createCancelOrRefundRequest(AdyenRequestFactory.java:492) ~[classes/:?]
INFO   | jvm 1    | main    | 2021/01/04 13:29:30.991 |    at com.adyen.v6.service.DefaultAdyenPaymentService.cancelOrRefund(DefaultAdyenPaymentService.java:269) ~[classes/:?]
```
 
**Additional context**
It's not really clear why it get injected as null, since in **adyen-spring.xml** the property is correctly injected:
```xml
<bean id="adyenRequestFactory" class="com.adyen.v6.factory.AdyenRequestFactory">
    <property name="configurationService" ref="configurationService" />
</bean>
```
It seems that
```java
public void setConfigurationService(ConfigurationService configurationService) {
    this.configurationService = configurationService;
}
```
is never called.

Altough we do have a solution for the same (actually multiple), I would like to raise (ad as suggested by your support, with ticket **#1797512**) it even here

**Comment by saquibsayyad** [comment]
Hi @abonforti ,

We investigated this issue internally and in our case the configuration service do gets injected. You can see it in attached screenshot.

It looks like something is different in your environment.
![Screen Shot 2021-01-13 at 5 27 46 PM](https://user-images.githubusercontent.com/16626736/104587300-0a569a00-5667-11eb-8542-c32115ff5372.png)


Thanks,
Saquib
