### ISSUE TITLE
Adyen Report Available Notification Merchant Reference is null 

### ISSUE THREAD

**Issue by erhanturksel** [Adyen/adyen-hybris#234]
We can successfully get an notification when report available notification is available. But merchantReference field is null 
 on NotificationItemModel object.That's why we encounter problems during new notification check.

**To Reproduce**
1.Get  report available notification 
2.Check merchantReference field on NotificationItemModel
3.Run adyenProcessNotificationCronJob
4.check isNewerNotificationExists merhod İf merchantReference is null

**My workaround  is set as empty string merchantReference field when running cronjob.

**Comment by saquibsayyad** [comment]
Hi @erhanturksel,

Thanks for reporting this issue, we are checking it internally and will fix it ASAP.

Regards,
Saquib
Adyen
