### ISSUE TITLE
Payment transaction entry without amount for cancel request

### ISSUE THREAD

**Issue by charles-moreel** [Adyen/adyen-hybris#236]
**Describe the bug**
When a cancel request is processed the payment transaction entry saved for this request is missing the amount and the currency.
In AdyenVoidCommand class, the totalAmount and currency are not set in the VoidResult.

**Expected behavior**
To have a payment transaction entry with amount and currency for a cancel request

**Comment by rcaroen** [comment]
Thanks for that

Tape à l'oeil
