### ISSUE TITLE
IE 11 - problems with Arrow function

### ISSUE THREAD

**Issue by chrizzle79** [Adyen/adyen-hybris#239]
**Describe the bug**
In IE 11 
![image](https://user-images.githubusercontent.com/26418737/107746072-90710980-6d15-11eb-8931-6b8ed32d7a6a.png)

a syntax error occurs in the adyen.checkout.js line: 319 column: 46.

`onChange: (state, component) => {
                    if (!state.isValid) {
                        this.enablePlaceOrder(label);
                    }
                }`

The checkout can not be finished.

Used plugin version: 9.0

**To Reproduce**
1. Use an IE 11 browser in SAP Commerce
2. At least go through the checkout
3. Check in DEV tools (F12) and see the syntax error

**Expected behavior**
Checkout gets finished

**Desktop (please complete the following information):**
 - Browser IE 11

**Comment by chrizzle79** [comment]
Any news on this issue?

**Comment by saquibsayyad** [comment]
Hi @chrizzle79 ,

Thanks for reporting the issue. We are checking it internally and will fix it soon.

Regards,
Saquib
Adyen

**Comment by saquibsayyad** [comment]
Issue is fixed and will be available in next release.
