### ISSUE TITLE
AdyenCaptureCommand equals

### ISSUE THREAD

**Issue by RicardofVallejo** [Adyen/adyen-hybris#248]
On class AdyenCaptureCommand:96 in extension adyenv6core modification result is a string and is being compared with "==" instead of .equals...

Not working.

**Comment by saquibsayyad** [comment]
Hi @RicardofVallejo,

Thanks for raising this issue. We will fix it and include it next release.

Regards,
Saquib
Adyen

**Comment by saquibsayyad** [comment]
Closing the issue, fix will be available in next release.
