### ISSUE TITLE
No alert shown when no payment method selected

### ISSUE THREAD

**Issue by andykps** [Adyen/adyen-hybris#253]
https://github.com/Adyen/adyen-hybris/blob/47b39de21c684793a467c060d752ea18c0dbaaf1/adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js#L67

We're not seeing an error when no payment method is selected. It doesn't actually submit the form because the undefined `paymentMethod` variable causes an exception further down at https://github.com/Adyen/adyen-hybris/blob/47b39de21c684793a467c060d752ea18c0dbaaf1/adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js#L86

I'm not a JS developer but shouldn't this be `if (!paymentMethod)` instead?
I don't know if this is browser specific i.e. do some browser return an empty string for an unselected radio button and some return undefined? I'm using Vivaldi 3.8.2259.40 UA is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.95 Safari/537.36

**Comment by saquibsayyad** [comment]
Hi @andykps,

Thanks for reporting the issue. We are checking it internally and will fix it soon.

Regards,
Saquib
Adyen

**Comment by olga-adyen** [comment]
Hi @andykps we have added this issue to the backlog. 

Thank you!
