### ISSUE TITLE
Parameter redirect_result does not exists for illicado_prosody payment

### ISSUE THREAD

**Issue by syfontaine** [Adyen/adyen-hybris#254]
Adyen response with a prosodie_illicado payment
is not "redirect_result" but "payload".
I modified the code to make it work.

Here is my modification.

**private static final String PAYLOAD = "payload";**
` public String handleAdyenResponse(final HttpServletRequest request, final RedirectAttributes redirectModel) {
        final String redirectResult = request.getParameter(REDIRECT_RESULT);
        final HashMap<String, String> details = new HashMap<>();

        if (redirectResult != null && !redirectResult.isEmpty()) {
            details.put(REDIRECT_RESULT, redirectResult);
        } else {
            **details.put(REDIRECT_RESULT, request.getParameter(PAYLOAD));**
        }`

Can you take this modification into account in a future release?

Thanks.

**Comment by saquibsayyad** [comment]
Hi @syfontaine,

Thanks for reporting the issue. We are looking at it.

Thanks,
Saquib
Adyen

**Comment by rcaroen** [comment]
Hello @saquibsayyad ,
Do you have any news on this?
Regards

**Comment by olga-adyen** [comment]
@rcaroen hi, we have added this issue to the backlog. 
Thank you!
