### ISSUE TITLE
ConfigurationService in DefaultAdyenCheckoutFacade has no getter

### ISSUE THREAD

**Issue by Mikolaj-Tworek-Eclipse** [Adyen/adyen-hybris#282]
**Is your feature request related to a problem? Please describe.**
I cannot use configurationService from DefaultAdyenCheckoutFacade in my derived class. 

**Describe the solution you'd like**
Could you add getter for ConfigurationService?

**Describe alternatives you've considered**
No alternatives

**Additional context**
-

**Comment by olga-adyen** [comment]
Hi @Mikolaj-Tworek-Eclipse thank you for your suggestion. We have added this into the backlog. I will close this issue.
