### ISSUE TITLE
AdyenRequestFactory is not considering rounding issues on setOpenInvoiceData

### ISSUE THREAD

**Issue by alexanklas-elkjop** [Adyen/adyen-hybris#284]
**Describe the bug**
com.adyen.v6.factory.AdyenRequestFactory#setOpenInvoiceData(com.adyen.model.checkout.PaymentsRequest, de.hybris.platform.commercefacades.order.data.CartData) 

com.adyen.v6.factory.AdyenRequestFactory#setOpenInvoiceData(com.adyen.model.PaymentRequest, de.hybris.platform.commercefacades.order.data.CartData, de.hybris.platform.core.model.user.CustomerModel)

both call 

// Use totalPrice because the basePrice does include tax as well if you have configured this to be calculated in the price
BigDecimal pricePerItem = entry.getTotalPrice().getValue().divide(new BigDecimal(entry.getQuantity()));

without a scale, which leads to

java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.

In cases you have a promotion which gives you a value that needs rounding after division

**To Reproduce**
1. have a entry with a qty of 3 and an order entry total of 100
2. try to authorize klarna invoice payment

**Expected behavior**
Use a scale to avoid rounding issues

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pjaneta** [comment]
Investigation is in progress
