### ISSUE TITLE
Notifications are not filtered by PSP reference in NotificationItemRepository#isNewerNotificationExists

### ISSUE THREAD

**Issue by massimo-chericoni** [Adyen/adyen-hybris#285]
When a failed payment is immediately followed by a successful payment (maybe because the customer has input a wrong CVC the first time) we receive 3 notifications in SAP Commerce from Adyen: two are notifications for the declined payment and one is for the successful one.
However, the notifications are ordered by event date, and it can be seen in the attached screenshot that the successful notification is in between the two failed ones.
The screenshot shows the result of the query:
`select * from {NotificationItem} where {merchantReference}='A21587156'`

<img width="855" alt="Screenshot 2022-10-11 at 14 56 45" src="https://user-images.githubusercontent.com/115563125/195111057-2a638659-6342-4fff-82cb-eb7ca03abffd.png">

When the cron job `AdyenProcessNotificationCronJob` processes the notifications, it checks if a newer notification exists, and in that case it skips the older ones, but, and here’s the problem, the notifications are filtered only by merchantReference and merchantAccountCode which means the 3rd failed notification is seen as a newer one, even if the PSP reference is different, and the successful notification, being older, is skipped. This logic is in `NotificationItemRepository#isNewerNotificationExists`.

I think the query in `NotificationItemRepository#isNewerNotificationExists` should take into account also the PSP reference of the notification when determining if a newer version exists.

It wouldn't be a problem if we only received 1 notification for the failed payment followed by 1 notification for the successful payment, but we do get a second notification for the failed payment.

**Comment by kpieloch** [comment]
We investigating the issue.
