### ISSUE TITLE
Upgrade to the latest JS/JavaAPI and Rest API endpoints 

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-hybris#287]
**Is your feature request related to a problem? Please describe.**
Many functionalities and new payment methods are MISSING like Co-branded cards, PayPal Express and so on.

**Describe the solution you'd like**
To keep the adyen hybris plugin up2date with every release of adyen APIs and changes so third parties can have a secure, updated solution

**Describe alternatives you've considered**
Currently the only alternative is to not use the adyen-hybris plugin if we want to use the newest apis, the upgrade from older versions to the newer ones is impossible without rewriting huge chunks of the code.

**Additional context**
The Adyen Hybris extension is quite old. This release is from 24 Feb 2022 

It is using some very old Java libraries and JS libraries and API levels from Adyen 

[adyen-java-api-library](https://github.com/Adyen/adyen-java-api-library) (v14.0.0)

[adyen-web](https://github.com/Adyen/adyen-web) (v4.3.1)

[Adyen Checkout API](https://docs.adyen.com/api-explorer/) (v67)
The latest as of now are : 

adyen-java-api-library 18.1.13

adyen web version v5.28.1

Checkout API v69

We are currently waiting for PayPal Express with delivery options with different prices which will be released in Q1 2023 I have been told with the current speed of adyen hybris upgrades if this is indeed released in the JS/API level in Q1 2023 maybe this plugin will catch up with it in 2025.. which is less then ideal.

**Comment by pjaneta** [comment]
In newest (11.1.0) version there are:

- [adyen-java-api-library](https://github.com/Adyen/adyen-java-api-library) (v18.1.3)
- [adyen-web](https://github.com/Adyen/adyen-web) (v5.25.0)
- [Adyen Checkout API](https://docs.adyen.com/api-explorer/) (v69)

Further library version updates are in progress
