### ISSUE TITLE
Payment method "Blik" needed

### ISSUE THREAD

**Issue by sadiqueali1** [Adyen/adyen-hybris#293]
We need to have "BLIK" as a payment method in the Hybris/SAP add-on.

When I requested Adyen support I got the information, the BLIK payment is not supported 

For a webshop rollout to Pland in Q2 2023 we need to have "BLIK" as a payment option, as this is the most used payment option in POLAND.

Here: https://docs.adyen.com/plugins/hybris/supported-payment-methods I've seen, that this is currently not supported.
I need a quick answer if this is possible and how long the implementation would take.

Are there other possibilities to integrate it into an SAP web shop beside the currently used Drop-in?
https://docs.adyen.com/online-payments/web-drop-in
https://docs.adyen.com/payment-methods/blik/web-drop-in

**Comment by sadiqueali1** [comment]
Hello Adyen Team 
Do you have an update on this request ?

**Comment by akoz-adyen** [comment]
Hello @sadiqueali1,

We will release Blik support in the next update to the plugin (ETA July 10th)

**Comment by kpieloch** [comment]
BLIK is added in release 11.1.0 .
