### ISSUE TITLE
NullPointerException when the PaymentResult doesn't contain a fraud report

### ISSUE THREAD

**Issue by arobirosa** [Adyen/adyen-hybris#40]
How the error is triggered:
1. Test card details are entered into the Hybris cart
2. The user places an order and the method com.adyen.v6.facades.AdyenCheckoutFacade#authoriseCardPayment is called
3. The payment is successfully authorized and com.adyen.v6.facades.AdyenCheckoutFacade#createAuthorizedOrder is called
4. Then com.adyen.v6.service.AdyenOrderService#createFraudReportFromPaymentResult returns null because there isn't any fraud report on the payment result.
5. The method com.adyen.v6.service.AdyenOrderService#storeFraudReportFromPaymentResult expects a non-null result and there is a NPE on line 76.

Test credit card used: 2223 0000 4841 0010 - 08/2018 - 737
Sourcecode: Rev. 38779620cffd7344e92b010b9050fb27616dc950

Returned payment Result:
class PaymentResult {
    authCode: 74886
    paRequest: null
    issuerUrl: null
    md: null
    dccAmount: null
    dccSignature: null
    pspReference: 8824950126110927
    resultCode: Authorised
    additionalData: {paymentMethod=mc}
    refusalReason: null
    fraudResult: null
}

[stacktrace.txt](https://github.com/Adyen/adyen-hybris/files/1007160/stacktrace.txt)

**Comment by lancergr** [comment]
Hi @arobirosa 
Thanks for reporting this! I will push a fix for it.

However, I would strongly suggest to enable the fraud reports in your account.
If you would like to enable them, please send an e-mail to plugin@adyen.com with your merchant account code.

Best Regards,
Giorgos
Adyen

**Comment by arobirosa** [comment]
Hi @lancergr 
Thanks for your fast answer and correction. My customer will provide me a test merchant account. I hope that thy have turned on the fraud reports there.

Thanks!
