### ISSUE TITLE
AdyenSummaryCheckoutStepController should't use a yacceleratorstorefront class

### ISSUE THREAD

**Issue by maciek-marcinkowski** [Adyen/adyen-hybris#42]
Currently AdyenSummaryCheckoutStepController is extending de.hybris.platform.yacceleratorstorefront.controllers.pages.checkout.steps.SummaryCheckoutStepController which blocks a possibility to use an addon in case of custom created accelerators (where packages are named differently). It should extend de.hybris.platform.acceleratorstorefrontcommons.controllers.pages.checkout.steps.AbstractCheckoutStepController in order to avoid such a problems

**Comment by rikterbeek** [comment]
Hi @maciek-marcinkowski,

Many thanks for this improvement and great that you have done a PR. Let's continue the discussion int the PR https://github.com/Adyen/adyen-hybris/pull/43

Regards,
Rik
Adyen
