### ISSUE TITLE
Use official adyen-java-api-library

### ISSUE THREAD

**Issue by bjmi** [Adyen/adyen-hybris#70]
**Hybris version**: 6.1.0.3
**Description**
adyen-hybris (tag 3.3.0) contains a patched  version  of `adyen-java-api-library-1.3.0.jar` in extension location adyenv6core/lib/adyen-java-api-library-1.3.0.jar (2018-01-31)

Maven Central library at https://repo.maven.apache.org/maven2/com/adyen/adyen-java-api-library/1.3.0/adyen-java-api-library-1.3.0.jar (2017-12-22)
doesn't contain e.g.
* PaymentRequest.setEncryptedCardNumber(...)
* PaymentRequest.setCardHolder(...)
* PaymentRequest.setEncryptedExpiryMonth(...)
* PaymentRequest.setEncryptedExpiryYear(...)
* PaymentRequest.setEncryptedSecurityCode(...)

Please release a new version of `adyen-java-api-library-1.3.0.jar` in Maven central that contains latest changes (v1.3.1 ?)

Thanks in advance!

**Comment by lancergr** [comment]
Hi @bjmi 

We have released today the version 1.4.0 of adyen-java-api-library, which contains the changes you mentioned. Hope that works for you!

Kind Regards,
Giorgos
Adyen

**Comment by bjmi** [comment]
Great and thanks.

Btw: new overload of `HMACValidator.calculateHMAC(NotificationRequestItem notificationRequestItem, String key)` causes compile error in [AdyenCheckoutFacadeTest](https://github.com/Adyen/adyen-hybris/blob/3.3.0/adyenv6b2ccheckoutaddon/testsrc/com/adyen/v6/facades/AdyenCheckoutFacadeTest.java#L138)

**Comment by lancergr** [comment]
Hi @bjmi 

Indeed, you will need to adapt the tests in case of upgrade to 1.4.0.
I have pushed the relevant change here 725c337

Best Regards,
Giorgos
Adyen
