### ISSUE TITLE
DisableResult evaluation doesn't fit to /disable API

### ISSUE THREAD

**Issue by bjmi** [Adyen/adyen-hybris#72]
Hi,

we currently use `com.adyen.v6.service.DefaultAdyenPaymentService#disableStoredCard` from adyenv6core (3.3.0).
Executing disableStoredCard(..) always returns **false** because there are no details within response.

E.g. `{"response":"[detail-successfully-disabled]"}` is returned as documented at https://docs.adyen.com/developers/features/recurring-payments/disable-stored-details#response i.e. the evaluation of disable result doesn't fit to /disable API.

Possible solution: DisableResult should check for presence of `[detail-successfully-disabled]` or `[all-details-successfully-disabled]` at https://github.com/Adyen/adyen-hybris/blob/4bd3ad3a36dc7b96493d959a27a891c6ae6e2c2a/adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java#L247

I hope I understand the API correctly.

**Comment by lancergr** [comment]
Hi @bjmi 

Indeed checking on the result ([detail-successfully-disabled]) is better way on determining the outcome of disable call.
Unless you are interested on opening a PR for this, we will push a fix for it so that is included on the next releases!

Best Regards,
Giorgos
Adyen

**Comment by lancergr** [comment]
Resolved in #75
